### PR TITLE
Add Civil Legal Aid reporting landscape

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

I wanted to capture the overview of Civil Legal Aid reporting:

1. One of our CLA systems produces a complete dump of data in a zip file.
1. This file is then downloaded, then subsequently uploaded to another system by a person.
1. The target system transforms the data into "subject areas" for analytical and reporting use and stores it in a database.
1. The database is used as a data source in our business intelligence system.

## Why make these changes?

This process is not widely known. It's only [documented in text](https://dsdmoj.atlassian.net/wiki/spaces/CPO/pages/1570177156/Uploading+Civil+Legal+Aid+data+to+CLA+MI+Apex), and visuals > text 🤘

### CODE REVIEW

**Comment by sldblog** [comment]
@exonian @said-moj Could you review this when you have a moment, please?

**Comment by said-moj** [comment]
`uses it to retrieve reports with civil legal aid data`
I was bit confused what `it` mean here, would `retrieves reports with civil legal aid data` have the same meaning here

**Comment by sldblog** [comment]
@said-moj Done in ae1bd9b5ac67bc1b67a824e207dfce3e899a2d9f

**Comment by sldblog** [comment]
🏆 🍹 🐠 🙇 🎩

**Pull request merged**
